<a href="https://colab.research.google.com/github/MRUTYUNJAYAMOHANTY/Python/blob/master/Libraries/Numpy/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Load in NumPy (remember to pip install numpy first)

In [1]:

import numpy as np

The Basics

In [4]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]
